# Generated by Django 5.1.6 on 2025-03-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blockedapp_blockedwebsite_focussession'),
    ]

    operations = [
        migrations.AddField(
            model_name='focussession',
            name='focus_score',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='focussession',
            name='interruptions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='focussession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
