# Generated by Django 5.1.6 on 2025-03-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_focussession_focus_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedapp',
            name='is_whitelisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blockedapp',
            name='package_name',
            field=models.CharField(default='com.example.default', max_length=255),
        ),
        migrations.AddField(
            model_name='blockedwebsite',
            name='is_whitelisted',
            field=models.BooleanField(default=False),
        ),
    ]
