# Generated by Django 5.1.6 on 2025-03-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blockedapp_is_whitelisted_blockedapp_package_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='focussession',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='focussession',
            name='hard_lock',
            field=models.BooleanField(default=False),
        ),
    ]
