# Generated by Django 5.1.6 on 2025-03-31 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_focussession_cooldown_until_focussession_hard_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedapp',
            name='package_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('reading_duration', models.PositiveIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('interruptions', models.PositiveIntegerField(default=0)),
                ('focus_score', models.PositiveIntegerField(default=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FocusSession',
        ),
    ]
