# Generated by Django 5.1.6 on 2025-04-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_blockedapp_package_name_readingsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsession',
            name='hard_lock',
            field=models.BooleanField(default=False),
        ),
    ]
