# Generated by Django 5.1.6 on 2025-04-02 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_readingsession_hard_lock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockedapp',
            name='is_whitelisted',
        ),
        migrations.RemoveField(
            model_name='blockedwebsite',
            name='is_whitelisted',
        ),
    ]
